package k6script

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/wreckr/wreckr/apps/api/internal/scenario"
)

type Script struct {
	Name    string
	Content string
}

func Compile(sc scenario.Scenario) (Script, error) {
	sc = sc.WithEnv().Normalized()
	if err := sc.Validate(); err != nil {
		return Script{}, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by Wreckr from scenario %q.\n", sc.Name)
	b.WriteString("// Execute with: k6 run <script.js>\n\n")
	b.WriteString("import http from 'k6/http';\n")
	b.WriteString("import { check, sleep } from 'k6';\n\n")
	writeOptions(&b, sc)
	fmt.Fprintf(&b, "const BASE_URL = %s;\n", jsString(sc.Target.BaseURL))
	fmt.Fprintf(&b, "const TARGET_HEADERS = %s;\n\n", jsValue(sc.Target.Headers))
	writeHelpers(&b)
	writeLifecycle(&b, "setup", sc.Setup, sc)
	writeDefault(&b, sc)
	writeLifecycle(&b, "teardown", sc.Teardown, sc)
	writeInvariantNotes(&b, sc)

	return Script{Name: sc.Name, Content: b.String()}, nil
}

func writeOptions(b *strings.Builder, sc scenario.Scenario) {
	b.WriteString("export const options = {\n")
	fmt.Fprintf(b, "  scenarios: {\n")
	fmt.Fprintf(b, "    wreckr: {\n")
	fmt.Fprintf(b, "      executor: 'shared-iterations',\n")
	fmt.Fprintf(b, "      vus: %d,\n", sc.Traffic.Concurrency)
	fmt.Fprintf(b, "      iterations: %d,\n", k6Iterations(sc))
	fmt.Fprintf(b, "      maxDuration: '10m',\n")
	fmt.Fprintf(b, "    },\n")
	fmt.Fprintf(b, "  },\n")
	if sc.Traffic.RatePerSecond > 0 {
		fmt.Fprintf(b, "  rps: %d,\n", sc.Traffic.RatePerSecond)
	}
	thresholds := k6Thresholds(sc)
	if len(thresholds) > 0 {
		b.WriteString("  thresholds: {\n")
		keys := make([]string, 0, len(thresholds))
		for key := range thresholds {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(b, "    %s: %s,\n", jsString(key), jsValue(thresholds[key]))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")
}

func writeHelpers(b *strings.Builder) {
	b.WriteString(`function buildURL(path) {
  if (path.startsWith('http://') || path.startsWith('https://')) {
    return path;
  }
  return new URL(path, BASE_URL).toString();
}

function headers(extraHeaders) {
  return Object.assign({}, TARGET_HEADERS, extraHeaders || {});
}

function bodyFor(request) {
  if (request.json !== undefined) {
    return JSON.stringify(request.json);
  }
  if (request.body !== undefined) {
    return request.body;
  }
  return null;
}

function runRequest(request) {
  const params = {
    headers: headers(request.headers),
    tags: { name: request.name, phase: request.phase || 'request' }
  };
  const body = bodyFor(request);
  if (request.json !== undefined && params.headers['Content-Type'] === undefined) {
    params.headers['Content-Type'] = 'application/json';
  }
  const response = http.request(request.method, buildURL(request.path), body, params);
  const expected = request.expected_statuses;
  const checks = {};
  checks[request.name + ' status'] = (r) => expected.length > 0 ? expected.includes(r.status) : r.status < 500;
  check(response, checks);
  return response;
}

`)
}

func writeLifecycle(b *strings.Builder, name string, requests []scenario.Request, sc scenario.Scenario) {
	if len(requests) == 0 {
		return
	}
	fmt.Fprintf(b, "export function %s() {\n", name)
	fmt.Fprintf(b, "  const requests = %s;\n", jsValue(k6Requests(requests, name)))
	b.WriteString("  for (const request of requests) {\n")
	b.WriteString("    runRequest(request);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
}

func writeDefault(b *strings.Builder, sc scenario.Scenario) {
	fmt.Fprintf(b, "export default function () {\n")
	fmt.Fprintf(b, "  const requests = %s;\n", jsValue(k6Requests(sc.Requests, "request")))
	if sc.Traffic.Type == scenario.TrafficRetryStorm {
		attempts := sc.Traffic.Retry.Attempts
		if attempts <= 0 {
			attempts = 3
		}
		fmt.Fprintf(b, "  for (let attempt = 0; attempt < %d; attempt += 1) {\n", attempts)
		b.WriteString("    for (const request of requests) {\n")
		b.WriteString("      runRequest(request);\n")
		b.WriteString("    }\n")
		if sc.Traffic.Retry.BackoffMS > 0 {
			fmt.Fprintf(b, "    sleep(%s);\n", strconv.FormatFloat(float64(sc.Traffic.Retry.BackoffMS)/1000, 'f', 3, 64))
		}
		b.WriteString("  }\n")
	} else {
		b.WriteString("  for (const request of requests) {\n")
		b.WriteString("    runRequest(request);\n")
		b.WriteString("  }\n")
	}
	b.WriteString("}\n\n")
}

func writeInvariantNotes(b *strings.Builder, sc scenario.Scenario) {
	if len(sc.Invariants) == 0 {
		return
	}
	b.WriteString("// Wreckr invariants from the source scenario:\n")
	for _, inv := range sc.Invariants {
		switch inv.Type {
		case "http_probe":
			fmt.Fprintf(b, "// - %s: http_probe %s %s with json_path %q\n", inv.Name, inv.Method, inv.Path, inv.Expect.JSONPath)
		case "response_count":
			fmt.Fprintf(b, "// - %s: response_count for request %q and status %s\n", inv.Name, inv.Request, invariantStatus(inv))
		default:
			fmt.Fprintf(b, "// - %s: %s\n", inv.Name, inv.Type)
		}
	}
	b.WriteString("// Exact invariant evaluation remains a Wreckr report responsibility.\n")
}

func k6Iterations(sc scenario.Scenario) int {
	if sc.Traffic.Type == scenario.TrafficRace {
		return sc.Traffic.Concurrency * sc.Traffic.Iterations
	}
	return sc.Traffic.Iterations
}

func statusCodesToTrack(req scenario.Request) []int {
	codes := []int{0, 200, 201, 204, 400, 401, 403, 404, 409, 500, 502, 503, 504}
	for _, c := range req.Expect.Status {
		found := false
		for _, existing := range codes {
			if existing == c {
				found = true
				break
			}
		}
		if !found {
			codes = append(codes, c)
		}
	}
	return codes
}

func k6Thresholds(sc scenario.Scenario) map[string][]string {
	out := map[string][]string{}
	if sc.Thresholds.P95MS != nil {
		out["http_req_duration"] = append(out["http_req_duration"], fmt.Sprintf("p(95)<=%.1f", *sc.Thresholds.P95MS))
	}
	if sc.Thresholds.MaxErrorRate != nil {
		successRate := 1 - *sc.Thresholds.MaxErrorRate
		out["checks"] = append(out["checks"], fmt.Sprintf("rate>=%.4f", successRate))
	}

	// Add dummy thresholds for status code tracking per request name and status code
	for _, req := range sc.Setup {
		for _, code := range statusCodesToTrack(req) {
			key := fmt.Sprintf("http_reqs{name:%q,status:%d}", req.Name, code)
			out[key] = []string{"count>=0"}
		}
	}
	for _, req := range sc.Requests {
		for _, code := range statusCodesToTrack(req) {
			key := fmt.Sprintf("http_reqs{name:%q,status:%d}", req.Name, code)
			out[key] = []string{"count>=0"}
		}
	}
	for _, req := range sc.Teardown {
		for _, code := range statusCodesToTrack(req) {
			key := fmt.Sprintf("http_reqs{name:%q,status:%d}", req.Name, code)
			out[key] = []string{"count>=0"}
		}
	}
	return out
}

type compiledRequest struct {
	Name             string            `json:"name"`
	Method           string            `json:"method"`
	Path             string            `json:"path"`
	Headers          map[string]string `json:"headers,omitempty"`
	JSON             any               `json:"json,omitempty"`
	Body             string            `json:"body,omitempty"`
	ExpectedStatuses []int             `json:"expected_statuses"`
	Phase            string            `json:"phase,omitempty"`
}

func k6Requests(requests []scenario.Request, phase string) []compiledRequest {
	out := make([]compiledRequest, 0, len(requests))
	for _, req := range requests {
		compiled := compiledRequest{
			Name:             req.Name,
			Method:           req.Method,
			Path:             req.Path,
			Headers:          req.Headers,
			Body:             req.Body,
			ExpectedStatuses: req.Expect.Status,
			Phase:            phase,
		}
		if len(req.JSON) > 0 {
			var body any
			if err := json.Unmarshal(req.JSON, &body); err == nil {
				compiled.JSON = body
			}
		}
		out = append(out, compiled)
	}
	return out
}

func invariantStatus(inv scenario.Invariant) string {
	if inv.Status == nil {
		return "any"
	}
	return strconv.Itoa(*inv.Status)
}

func jsString(value string) string {
	return jsValue(value)
}

func jsValue(value any) string {
	var raw bytes.Buffer
	enc := json.NewEncoder(&raw)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(value)
	var out bytes.Buffer
	_ = json.Indent(&out, bytes.TrimSpace(raw.Bytes()), "", "  ")
	return out.String()
}
